version: "2.2"

services:
  backend:
    container_name: shop-scraper
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    image: node:18.13.0-alpine
    command: ["yarn", "start"]
    volumes:
      - ".:/usr/src/app"
    networks:
      - shop-be
  #
  #                   __ __            __             __
  #   .----.-----.--|  |__.-----.----|  .--.--.-----|  |_.-----.----.
  #  |   _|  -__|  _  |  |__ --|  __|  |  |  |__ --|   _|  -__|   _|
  # |__| |_____|_____|__|_____|____|__|_____|_____|____|_____|__|
  #
  #
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
      - 6380:6379
    volumes:
      - redis-node-0-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
      - 6381:6379
    volumes:
      - redis-node-1-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-noxde-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
        - 6382:6379
    volumes:
      - redis-node-2-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
        - 6383:6379
    volumes:
      - redis-node-3-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
        - 6384:6379
    volumes:
      - redis-node-4-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
        - 6385:6379
    volumes:
      - redis-node-5-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-node-6:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
        - 6386:6379
    volumes:
      - redis-node-6-data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'

  redis-cluster:
    image: docker.io/bitnami/redis-cluster:6.2
    networks:
      - shop-be
    ports:
        - 6379:6379
    volumes:
      - redis-cluster-data:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - 'REDIS_CLUSTER_CREATOR=yes'

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: storage
    hostname: azurite
    restart: always
    command: "azurite --blobHost 127.0.0.1 --blobPort 20003 --queueHost 127.0.0.1 --queuePort 20004 --tableHost 127.0.0.1 --tablePort 20005"
    ports:
      - "20003:20003"
      - "20004:20004"
      - "20005:20005"
    networks:
       - shop-be

networks:
  shop-be:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
volumes:
    redis-node-0-data:
    redis-node-1-data:
    redis-node-2-data:
    redis-node-3-data:
    redis-node-4-data:
    redis-node-5-data:
    redis-node-6-data:
    redis-cluster-data:
